### PR TITLE
Fix API Service-Account Cert

### PR DESCRIPTION
**Pull request by dmolik**
The API only verifies the token, while the controller-manager issues
it. See https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller
for more details

### CODE REVIEW

**Comment by jhunt** [comment]
why are you replacing a key file with a non-key file for an option that ends in `...-key-file`?

**Comment by dmolik** [comment]
Bad naming? https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/04-certificate-authority.md#the-service-account-key-pair

**Comment by dmolik** [comment]
Also, https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#configure-the-kubernetes-api-server

**Comment by jhunt** [comment]
For those following along at home. or in the future, who prefer to read English prose instead of communicating solely through links:

It appears that the problem is that the `--service-account-key-file` flag doesn't actually want the thing that is traditionally called the "key" in an X.509 certificate / key pair.  Hightower seems to gloss over this in _Kubernetes The Hard Way_.  The instructions have you generate a key pair, but the two halves get used in the following places:

- The **key** gets used by the controller-manager, since it has to issue the tokens.  This is realized in the `--service-account-private-key-file=/var/lib/kubernetes/service-account-key.pem` flag passed to `kube-controller-manager` [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#configure-the-kubernetes-controller-manager)
- The **certificate** gets used by the apiserver, which has to (I guess?) validate the tokens issued by the controller manager.  This is realized in the `--service-account-key-file=/var/lib/kubernetes/service-account.pem` flag passed to `kube-apiserver` [here](https://github.com/kelseyhightower/kubernetes-the-hard-way/blob/master/docs/08-bootstrapping-kubernetes-controllers.md#configure-the-kubernetes-api-server)

Perhaps the `--service-account-key-file` option just suffers from an unfortunate name.  It is possible that this used to be a symmetric key, instead of an asymmetric RSA public/private keypair.  Who knows?

@dmolik if you can _check my work_ above, I'd appreciate the expert eyes. ^_^

**Comment by dmolik** [comment]
Sorry, I was on my phone, and it was easier to post a link.

I'm not sure why Hightower glosses over it, my only guess is, brevity, as he has a section about deploying DNS to the cluster which requires a token. After glancing through the repo issues, I'm still not sure. 

I concur on your explanation. While this link, https://kubernetes.io/docs/reference/access-authn-authz/service-accounts-admin/#token-controller, discusses the command line, configuration, it doesn't explain why the naming scheme is confusing. I suppose going through the kubernetes repo history might give a better explanation, but alas I'm an Engineer, not a digital history d*****.

**Comment by jhunt** [comment]
Good enough for Hulk.

**Pull request merged**
