### PR TITLE
Support Containerd Registry Mirrors

### PR DESCRIPTION
**Pull request by jhunt**
This commit introduces containerd OCI registry mirroring, allowing
operators to run their own registries, complete with authantication
(user-based, certificate-based) etcd, to either shadow upstream names
like `postgres` (originally from docker.io), or to provide custom
private registries without giving out credentials to cluster users.

Also new is `manifests/mirrornetes`, a tinynetes configuration that
ships with multiple, separate registries, of varying configurations,
and custom mirror definitions to validate the implementation.

### CODE REVIEW

**Comment by obeyler** [comment]
to my part I prefer to keep the `insecure_skip_verify` rather than `verify` to point that you use an insecure repository. I think it's for this raison that containerd team uses this term. Docker team uses also the same term.

**Comment by jhunt** [comment]
I will definitely don't not unignore that feedback, @obeyler 😉

**Comment by obeyler** [comment]
ttar is what kind of tools ? is it like tar ?

**Comment by obeyler** [comment]
may you've got an error inside the auth part

**Comment by obeyler** [comment]
@jhunt Except my review about the `verify` parameter, I've tested this PR on my airgap environment and everything seems to be OK.

**Comment by obeyler** [comment]
@jhunt  At the end, I see you preferred to keep `verify` rather than `insecure_skip_verify` . 
Do you plan to make release soon ?

**Comment by jhunt** [comment]
I do indeed.  Given that K8s 1.19 is set to drop in early August, I wanted to get a 1.18.5 out today or tomorrow.  Is #50 going to be out of draft and ready for review before the end of the week?  If so, I'd like to include it in the release.

**Comment by obeyler** [comment]
@jhunt I'm not yet satisfied of #50  and as I need to do many other work before my holidays I think I can't finish it before august.

**Pull request merged**
